/**
 * Minimal i18n dictionary. English + Hindi for the MVP, structured so more
 * languages are just another key. UI chrome is translated; the triage content
 * itself comes back from the backend already in the chosen language.
 */
export const STRINGS = {
  en: {
    tagline: "Voice-first triage for India's pharmacy counters. We triage, never prescribe.",
    symptomsLabel: "Describe the symptoms",
    symptomsPlaceholder: "e.g. mild fever and body ache since yesterday",
    speak: "Speak",
    listening: "Listening…",
    stop: "Stop",
    age: "Age (optional)",
    currentMeds: "Current medicines (optional)",
    allergies: "Known allergies (optional)",
    addChip: "Add",
    triage: "Get triage",
    analyzing: "Analyzing safely…",
    reset: "New patient",
    print: "Print summary",
    listen: "Listen",
    demoTitle: "One-tap demo scenarios",
    consent: "Patient consents to processing these health details for this session.",
    safetyReasons: "Safety checks",
    followUps: "Suggested follow-up questions",
    otc: "OTC self-care guidance",
    emergency: "Emergency guidance",
    disclaimerTitle: "Important",
    signals: { SAFE: "Safe", CAUTION: "Caution", SEE_A_DOCTOR: "See a doctor" },
    rulesOnly: "Running in rules-only mode (LLM key not set). Safety rails are fully active.",
  },
  hi: {
    tagline: "भारत के फार्मेसी काउंटरों के लिए वॉइस-आधारित ट्राइएज। हम सलाह देते हैं, दवा नहीं लिखते।",
    symptomsLabel: "लक्षण बताइए",
    symptomsPlaceholder: "जैसे कल से हल्का बुखार और बदन दर्द",
    speak: "बोलें",
    listening: "सुन रहे हैं…",
    stop: "रोकें",
    age: "उम्र (वैकल्पिक)",
    currentMeds: "वर्तमान दवाइयाँ (वैकल्पिक)",
    allergies: "ज्ञात एलर्जी (वैकल्पिक)",
    addChip: "जोड़ें",
    triage: "ट्राइएज करें",
    analyzing: "सुरक्षित रूप से जाँच हो रही है…",
    reset: "नया मरीज़",
    print: "सारांश प्रिंट करें",
    listen: "सुनें",
    demoTitle: "एक-टैप डेमो परिदृश्य",
    consent: "मरीज़ इस सत्र के लिए ये स्वास्थ्य विवरण संसाधित करने की सहमति देता है।",
    safetyReasons: "सुरक्षा जाँच",
    followUps: "सुझाए गए अगले प्रश्न",
    otc: "ओटीसी स्व-देखभाल सलाह",
    emergency: "आपातकालीन सलाह",
    disclaimerTitle: "महत्वपूर्ण",
    signals: { SAFE: "सुरक्षित", CAUTION: "सावधानी", SEE_A_DOCTOR: "डॉक्टर से मिलें" },
    rulesOnly: "नियम-आधारित मोड में चल रहा है (LLM की नहीं है)। सुरक्षा नियम पूरी तरह सक्रिय हैं।",
  },
};
